# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# ////////////////
# blog 源码地址：https://github.com/vikapitoshka/blog

title: 元研究的网志

description: > # this means to ignore newlines until "baseurl:"
  Блог Виктории Капитоненко. Нужен для сохранения информации, полезной лично для меня, но которая обычно забывается.<br>
  Сайт написан на Jekyll и использует GitHub Pages.<br>
  Блог с открытым исходным кодом размещен на <a href="//github.com/ViKapitoshka/blog">github</a>.<br>
  Патчи, предложения и комментарии приветствуются.<br>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.kaptn.ru" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: '元研究'
  last_name: 'yuanyanjiu'
  avatar: '/images/avatar.jpeg'
  github_username:  wakemind  
  email: 245465151@qq.com
  telegram_name: vikapitoshka 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:title.html


