# Site settings
title: Isolated Joker
header-img: "img/facebook.jpg"
tagline: "cn"  
description: "乔书亚|追寻文字之美"  
baseurl: ""
url: "http://isolatedj.com"  

# About/contact
owner: 
  name: " Isolated Joker"
  email: isolatedj@yahoo.com
  bio: "千里之行，始于足下"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: img/favicon.png

douban_username:  isolatedj
twitter_username: isolatedj
github_username: isolatedj
facebook_username: isolatedj
weibo_username: isolatedj 
zhihu_username: isolatedj

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
rouge: pygments
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "IsolatedJ"
      header-img: "img/facebook.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : isolatedj
  disqus :
      short_name : isolatedj

# Analytics and webmaster tools stuff goes here
google_analytics: 
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation
