# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# ////////////////
# blog 源码地址：https://github.com/vikapitoshka/blog

title: 徐sir的网志

description: > # this means to ignore newlines until "baseurl:"
  无知识研究学习之地
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.kaptn.ru" # the base hostname & protocol for your site, e.g. http://example.com


author:
  name: '徐sir'
  last_name: 'yuanyanjiu'
  avatar: '/images/avatar.jpeg'
  github_username:  wakemind  
  email: 245465151@qq.com
  telegram_name: vikapitoshka 
  logo: '/images/logo.svg'

# Build settings
markdown: kramdown

permalink: /:categories/:title.html
#paginate: 2 # amount of posts to show
#paginate_path: 'javascript/page:num'
# Plugins
safe: false
 
# https://github.com/codestacks/jekyll-category-pagination
categories:
    pagination: 1
    generate_all: false
    directory: .
    details:
      #all: {}
      javascript:
        pagination: 1